CREATE TABLE product(
    id BIGINT GENERATED BY default AS IDENTITY, 
    name VARCHAR(255) NOT NULL, 
    picture_url VARCHAR(255)
);

CREATE TABLE product_info(
    product_id BIGINT NOT NULL, 
    name VARCHAR(255) NOT NULL, 
    price DOUBLE PRECISION
);

CREATE TABLE orders(
    id BIGINT GENERATED BY default AS IDENTITY, 
    status VARCHAR(255)
);

CREATE TABLE orders_date(
    order_id BIGINT NOT NULL,
    status VARCHAR(255),
    date_created DATE DEFAULT current_date
);

CREATE TABLE order_product(
    quantity INTEGER NOT NULL,
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL
);

CREATE INDEX idx_order_product_order_id ON order_product(order_id);
CREATE INDEX idx_order_product_product_id ON order_product(product_id);
CREATE INDEX idx_orders_date_order_id ON orders_date(order_id);
CREATE INDEX idx_product_info_product_id ON product_info(product_id);
